In [15]:
#Task 1 Solutions

transactions = [
    {"id": 1, "product": "Laptop", "price": 1200, "quantity": 2, "region": "EU"},
    {"id": 2, "product": "Phone", "price": 800, "quantity": -1, "region": "US"},
    {"id": 3, "product": "Tablet", "price": 0, "quantity": 5, "region": "EU"},
    {"id": 4, "product": "Monitor", "price": 350, "quantity": 3, "region": "US"},
    {"id": 5, "product": "Laptop", "price": 1200, "quantity": 1, "region": "EU"},
    {"id": 6, "product": "Keyboard", "price": 75, "quantity": 10, "region": "APAC"},
]
#a)
#Create empty list of dictionaries for filtered transactions
filtered_transactions = []

#Loop through each dictionary and filter out records where price is 0 or quantity is negative
for t in transactions:
    if t["price"] > 0 and t["quantity"] > 0:
        filtered_transactions.append(t)

#b) Create "total" field
for t in filtered_transactions:
    t["total"] = t["price"] * t["quantity"]

#c) Create new dictionary for grouping by region
revenue_by_region = {}

#Group by region and compute total revenue per region
for t in filtered_transactions:
    region = t["region"]
    total = t["total"]

    revenue_by_region[region] = revenue_by_region.get(region, 0) + total

#d) Find the region with the highest revenue and its specific revenue
max_region = max(revenue_by_region, key=revenue_by_region.get)
max_revenue = revenue_by_region[max_region]

#Print out the answer using an f-string
print(f"The region with the highest total revenue is {max_region} with a revenue of {max_revenue}")

The region with the highest total revenue is EU with a revenue of 3600


In [22]:
sales = [1200, 980, 1540, 870, 2010, 1650, 1300, 1100, 950, 1780, 2200, 1430, 1600, 1900]

#Creating the function and calculating the values of each key, returning a dictionary
def summarise_sales(sales):
    total_sales = sum(sales)
    average_sales = total_sales / len(sales)
    best_day_index = sales.index(max(sales)) + 1
    worst_day_index = sales.index(min(sales)) + 1
    above_average_count = sum(1 for s in sales if s > average_sales)
    
    return {"total": total_sales,
            "average": average_sales,
            "best_day": best_day_index,
            "worst_day": worst_day_index,
            "above_average_count": above_average_count
           }

#Printing the result by calling the function on the sales list
print(summarise_sales(sales))

{'total': 20510, 'average': 1465.0, 'best_day': 11, 'worst_day': 4, 'above_average_count': 7}


In [38]:
students = [
    {"name": "Anna", "grade": 85, "attendance": 0.92},
    {"name": "Erik", "grade": 58, "attendance": 0.75},
    {"name": "Mia", "grade": 91, "attendance": 0.98},
    {"name": "Leo", "grade": 44, "attendance": 0.60},
    {"name": "Sara", "grade": 72, "attendance": 0.88},
    {"name": "Tom", "grade": 67, "attendance": 0.70},
    {"name": "Nina", "grade": 95, "attendance": 0.99},
    {"name": "Olli", "grade": 50, "attendance": 0.65},
]
#a) Creating new list of passing students by filtering out those with a grade below 50
passing = []

for s in students:
    if s["grade"] >= 50:
        passing.append(s)

print(passing)
    
#b) Looping through each student and assigning a description based on the grade
for s in students:
    if s["grade"] >= 80:
        print(f"{s["name"]}: Excellent")
    elif s["grade"] >= 50:
        print(f"{s["name"]}: Pass")
    else:
        print(f"{s["name"]}: Fail")

#c) Looping through each student and incrementing the variable attendance_below_80_count by 1 each time a student has attendance below 0.80
attendance_below_80_count = 0

for s in students:
    if s["attendance"] < 0.80:
        attendance_below_80_count += 1

print(attendance_below_80_count)

#d) Initializing empty values for best student and their grade and looping through students, assigning them to the variables if their grade is better than the current grade
best_student = None
best_grade = 0

for s in students:
    if s["grade"] > best_grade:
        best_grade = s["grade"]
        best_student = s["name"]

print(f"The student with the highest grade is {best_student} with a grade of {best_grade}")

#e) First finding the highest grade using max(), and then finding the name of the student with that specific grade
max_grade = max([s["grade"] for s in students])
max_best_student = [s["name"] for s in students if s["grade"] == max_grade]

print(max_best_student, max_grade)

[{'name': 'Anna', 'grade': 85, 'attendance': 0.92}, {'name': 'Erik', 'grade': 58, 'attendance': 0.75}, {'name': 'Mia', 'grade': 91, 'attendance': 0.98}, {'name': 'Sara', 'grade': 72, 'attendance': 0.88}, {'name': 'Tom', 'grade': 67, 'attendance': 0.7}, {'name': 'Nina', 'grade': 95, 'attendance': 0.99}, {'name': 'Olli', 'grade': 50, 'attendance': 0.65}]
Anna: Excellent
Erik: Pass
Mia: Excellent
Leo: Fail
Sara: Pass
Tom: Pass
Nina: Excellent
Olli: Pass
4
The student with the highest grade is Nina with a grade of 95
['Nina'] 95


In [69]:
class Portfolio:
    def __init__(self, owner):
        self.owner = owner
        self.holdings = {}  # ticker -> {shares, price_per_share}

#a) Creating the method
    def add_asset(self, ticker, shares, price_per_share):
        #Checking if the ticker already exists in the portfolio
        if ticker in self.holdings:
            #Updating the amount of shares and price per share for existing ticker
            self.holdings[ticker]["shares"] += shares
            self.holdings[ticker]["price_per_share"] = price_per_share
        else:
            #Adding the new ticker if it does not exist already
            self.holdings[ticker] = {"shares": shares, "price_per_share": price_per_share}
#b) Looping through self.holdings using the method values(), giving us the values of the keys "shares" and "price_per_share"
    def total_value(self):
        total = 0
        for i in self.holdings.values():
            total += i["shares"] * i["price_per_share"]
        return total

#c) Initializing two empty variables, then checking if the value of the current ticker is larger than the variable
    def most_valuable(self):
        highest_value_ticker = None
        highest_value = 0
        
        for ticker, value  in self.holdings.items():
            current_value = value["shares"] * value["price_per_share"]

            #Replacing the values stored in the variables if current_value is larger than highest_value
            if current_value > highest_value:
                highest_value_ticker = ticker
                highest_value = current_value

        return highest_value_ticker
#d) Defining a __str__ method that prints the portfolio owners name, number of assets, and total value
    def __str__(self):
        assets = len(self.holdings)
        total = self.total_value()
        return(f"Portfolio Owner: {self.owner}, No. of Assets: {assets}, Total Value: {total}€")
            
portfolio = Portfolio("Jesper")
portfolio.add_asset("AAPL", 10, 150)
portfolio.add_asset("TSLA", 5, 700)
portfolio.add_asset("MSFT", 12, 320)
portfolio.add_asset("GOOGL", 8, 140)
print(portfolio.total_value())
print(portfolio.most_valuable())
print(portfolio)

9960
MSFT
Portfolio Owner: Jesper, No. of Assets: 4, Total Value: 9960€


In [88]:
orders = [
    ("2025-01-15", "Laptop"), ("2025-01-22", "Phone"),
    ("2025-02-03", "Laptop"), ("2025-02-14", "Tablet"),
    ("2025-03-01", "Phone"), ("2025-03-10", "Phone"),
    ("2025-03-22", "Laptop"), ("2025-04-05", "Monitor"),
]
#Importing the datetime module
import datetime

#Empty list for parsed dates
dates = []

#Parsing the date strings into datetime.date objects using strptime and appending the date objects to the list
for date, product in orders:
    d = datetime.datetime.strptime(date, "%Y-%m-%d").date()
    dates.append(d)

earliest_date = min(dates)
latest_date = max(dates)
days_between = (latest_date - earliest_date).days
print(days_between)

80


In [95]:
import numpy as np

# Rows: years (2022, 2023, 2024), Columns: quarters (Q1, Q2, Q3, Q4)
revenue = np.array([
    [210, 230, 190, 250],
    [220, 260, 200, 270],
    [250, 290, 230, 310]])

#a) Importing numpy and using sum and collapsing the columns to calculate annual revenue
annual_revenue = np.sum(revenue, axis=1)
print(annual_revenue)

#b) Calculating the mean of the quarters by collapsing the rows
mean_quarterly_revenue = np.mean(revenue, axis=0)
print(mean_quarterly_revenue)

#c) Multiplying the last row using an array of factors, then accessing the last row of the dataset and applying the factors
factors = np.array([1.05, 1.03, 1.08, 1.02])

revenue[-1] = revenue[-1] * factors
print(revenue)

#d)
boolean_index = revenue > 250
print(boolean_index)

[ 880  950 1080]
[226.66666667 260.         206.66666667 276.66666667]
[[210 230 190 250]
 [220 260 200 270]
 [262 298 248 316]]
[[False False False False]
 [False  True False  True]
 [ True  True False  True]]


In [127]:
import pandas as pd
#a)
#Creating the dataframe using pandas
data = pd.DataFrame({
    "employee": ["Anna", "Erik", "Mia", "Leo", "Sara", "Tom"],
    "department": ["Finance", "Marketing", "Finance", "IT", "Marketing", "IT"],
    "salary": [4500, 4000, 4800, 5200, 3900, 5100],
    "years_exp": [5, 3, 7, 10, 2, 8],
    "performance_score": [4.2, 3.8, 4.5, 4.0, 3.5, 4.9]
})

#Computing new column "salary_per_year_exp"
data["salary_per_year_exp"] = data["salary"] / data["years_exp"]

#Rounding the float to the nearest integer using round(0).astype(int)
data["salary_per_year_exp"] = data["salary_per_year_exp"].round(0).astype(int)

#b) Sorting the dataframe by performance_score and in descending order
data_sorted = data.sort_values(by="performance_score", ascending=False)
#Printing the top 3 performers
print(data_sorted.head(3))

#c) Using .loc along with boolean indexing to find the rows with a performance score above 4.0
print(data.loc[data["performance_score"] > 4.0])

#d) Renaming the years_exp column and replacing the existing dataframe using inplace=True
data.rename(columns={"years_exp": "experience_years"}, inplace=True)

#e) Locating the first four rows and accessing the correct columns by index
print(data.iloc[0:4, [2,4]])

data

  employee department  salary  years_exp  performance_score  \
5      Tom         IT    5100          8                4.9   
2      Mia    Finance    4800          7                4.5   
0     Anna    Finance    4500          5                4.2   

   salary_per_year_exp  
5                  638  
2                  686  
0                  900  
  employee department  salary  years_exp  performance_score  \
0     Anna    Finance    4500          5                4.2   
2      Mia    Finance    4800          7                4.5   
5      Tom         IT    5100          8                4.9   

   salary_per_year_exp  
0                  900  
2                  686  
5                  638  
   salary  performance_score
0    4500                4.2
1    4000                3.8
2    4800                4.5
3    5200                4.0


,employee,department,salary,experience_years,performance_score,salary_per_year_exp
0,Anna,Finance,4500,5,4.2,900
1,Erik,Marketing,4000,3,3.8,1333
2,Mia,Finance,4800,7,4.5,686
3,Leo,IT,5200,10,4.0,520
4,Sara,Marketing,3900,2,3.5,1950
5,Tom,IT,5100,8,4.9,638


In [135]:
import numpy as np
import pandas as pd

rng = np.random.default_rng(seed=123)
days = pd.date_range(start="2025-01-06", periods=28, freq="D")
visitors = rng.integers(200, 600, size=28)
conversion_rate = rng.uniform(0.02, 0.08, size=28).round(4)
avg_order_value = rng.normal(50, 10, size=28).round(2)

#a) Creating the dataframe, inserting the variables into the desired columns
data = pd.DataFrame({
    "date": days,
    "visitors": visitors,
    "conversion_rate": conversion_rate,
    "avg_order_value": avg_order_value
})

#Setting date as the index
data.set_index("date", inplace=True)

#b) Computing of new columns:
data["conversions"] = data["visitors"] * data["conversion_rate"]
#Rounding conversions column to nearest integer
data["conversions"] = data["conversions"].round(0).astype(int)

data["daily_revenue"] = data["conversions"] * data["avg_order_value"]

data



,visitors,conversion_rate,avg_order_value,conversions,daily_revenue
date,,,,,
2025-01-06,206,0.0645,64.30,13,835.90
2025-01-07,472,0.0578,48.44,27,1307.88
2025-01-08,437,0.0756,43.26,33,1427.58
2025-01-09,221,0.0339,43.61,7,305.27
2025-01-10,563,0.0679,49.39,38,1876.82
2025-01-11,288,0.0511,46.07,15,691.05
2025-01-12,302,0.0339,72.90,10,729.00
2025-01-13,273,0.0300,42.82,8,342.56
2025-01-14,333,0.0499,50.33,17,855.61
